# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 296ff9275b08d26b29624bf50485ce53c2ad53c341f657c9d7ec04e867be68e02333dac4e4c44ac5a27dbc818c4e2977c2b564a1d22a2c530597c91489fc8954

test:
  secret_key_base: 1fbcebee81db63ec680a3c6eb8c09066e9374f38ec6406fb181e9dc2a2110a8f8512778b9c3354caaff4a512c87f42d040b54500e9f0f25d69ccafa4530fba0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
