# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: klustter
  admin_email: klustter.codestore@gilioconsultoria.com
  admin_password: changeme
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  domain_name: gilioconsultoria.com
  secret_key_base: d31496865aa3b37915275ceacb52526145e2f25df2bc90498791055c4a449b575656000c956d4f4b936d2e2b40b175b5e4f19e6ab7c7e0e5e327787ef189f095

test:
  domain_name: gilioconsultoria.com
  secret_key_base: 0a24a583b1725af534b9b4f24b1e9a825785210fbec726fe5c52e8389e4eea1e5f504d3670a4307ee19bcff53cda065dd00537da6e347b171086b8c0070e86c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d31496865aa3b37915275ceacb52526145e2f25df2bc90498791055c4a449b575656000c956d4f4b936d2e2b40b175b5e4f19e6ab7c7e0e5e327787ef189f095
  admin_name: kadmin #<%= ENV["ADMIN_NAME"] %>
  admin_email: klustter.codestore@gilioconsultoria.com #<%= ENV["ADMIN_EMAIL"] %>
  admin_password: numseynivel3 #<%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: klustter.codestore@gilioconsultoria.com #<%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: abc123!@#
  domain_name: 10.11.50.154 #<%= ENV["DOMAIN_NAME"] %>
  secret_key_base: 25e40f155553cc3d412da431704954ceb7b28ae5d05316295dac62373285a2a3386495b92923b3b4362c3924da65fe31b1e26d869185506f8b4fd289863cafa3 #<%= ENV["SECRET_KE$
