class Status < ActiveRecord::Base
  has_one :script
  GRAVADO = 1
  VERIFICACAO_DUPLICIDADE = 2
  VERIFICACAO_CONSISTENCIA = 3
  VERIFICACAO_COMPLEXIDADE = 4
  VERIFICACAO_APROVADO = 5
  INICIAL = 6

end
